name: phone_number_mask_parser
description: ☎️ Dart package of simple parsing of phone numbers and various masking options.
version: 3.0.2
repository: https://github.com/ivangalkindeveloper/phone_number_mask_parser
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <4.0.0'

dev_dependencies:
  test: