import 'package:phone_number_mask/src/data.dart';

/// Main package constants
class PhoneNumberMaskConstant {
  static const List<PhoneNumberMaskCountry> countries = [
    PhoneNumberMaskCountry(
      title: "Afghanistan",
      phoneCode: "+93",
      alternativePhoneCodes: [],
      iso2Code: "AF",
      mask: "+## ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Albania",
      phoneCode: "+355",
      alternativePhoneCodes: [],
      iso2Code: "AL",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Algeria",
      phoneCode: "+213",
      alternativePhoneCodes: [],
      iso2Code: "DZ",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "United States",
      phoneCode: "+1",
      alternativePhoneCodes: [],
      iso2Code: "US",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "American Samoa",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1684",
      ],
      iso2Code: "AS",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Andorra",
      phoneCode: "+376",
      alternativePhoneCodes: [],
      iso2Code: "AD",
      mask: "+### ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Angola",
      phoneCode: "+244",
      alternativePhoneCodes: [],
      iso2Code: "AO",
      mask: "+### #### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Anguilla",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1264",
      ],
      iso2Code: "AI",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Antigua and Barbuda",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1268",
      ],
      iso2Code: "AG",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Argentina",
      phoneCode: "+54",
      alternativePhoneCodes: [],
      iso2Code: "AR",
      mask: "+## # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Armenia",
      phoneCode: "+374",
      alternativePhoneCodes: [],
      iso2Code: "AM",
      mask: "+### ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Aruba",
      phoneCode: "+297",
      alternativePhoneCodes: [],
      iso2Code: "AW",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Australia",
      phoneCode: "+61",
      alternativePhoneCodes: [],
      iso2Code: "AU",
      mask: "+## #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Austria",
      phoneCode: "+43",
      alternativePhoneCodes: [],
      iso2Code: "AT",
      mask: "+## ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Azerbaijan",
      phoneCode: "+994",
      alternativePhoneCodes: [],
      iso2Code: "AZ",
      mask: "+### ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Bahamas",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1242",
      ],
      iso2Code: "BS",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Bahrain",
      phoneCode: "+973",
      alternativePhoneCodes: [],
      iso2Code: "BH",
      mask: "+### ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Bangladesh",
      phoneCode: "+880",
      alternativePhoneCodes: [],
      iso2Code: "BD",
      mask: "+### ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Barbados",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1246",
      ],
      iso2Code: "BB",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Belarus",
      phoneCode: "+375",
      alternativePhoneCodes: [],
      iso2Code: "BY",
      mask: "+### (##) ###-##-##",
    ),
    PhoneNumberMaskCountry(
      title: "Belgium",
      phoneCode: "+32",
      alternativePhoneCodes: [],
      iso2Code: "BE",
      mask: "+## ### ## ## ##",
    ),
    PhoneNumberMaskCountry(
      title: "Belize",
      phoneCode: "+501",
      alternativePhoneCodes: [],
      iso2Code: "BZ",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Benin",
      phoneCode: "+229",
      alternativePhoneCodes: [],
      iso2Code: "BJ",
      mask: "+### ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Bermuda",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1441",
      ],
      iso2Code: "BM",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Bhutan",
      phoneCode: "+975",
      alternativePhoneCodes: [],
      iso2Code: "BT",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Bosnia and Herzegovina",
      phoneCode: "+387",
      alternativePhoneCodes: [],
      iso2Code: "BA",
      mask: "+### ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Botswana",
      phoneCode: "+267",
      alternativePhoneCodes: [],
      iso2Code: "BW",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Brazil",
      phoneCode: "+55",
      alternativePhoneCodes: [],
      iso2Code: "BR",
      mask: "+## (##) ####-####",
    ),
    PhoneNumberMaskCountry(
      title: "British Indian Ocean Territory",
      phoneCode: "+246",
      alternativePhoneCodes: [],
      iso2Code: "IO",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Bulgaria",
      phoneCode: "+359",
      alternativePhoneCodes: [],
      iso2Code: "BG",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Burkina Faso",
      phoneCode: "+226",
      alternativePhoneCodes: [],
      iso2Code: "BF",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Burundi",
      phoneCode: "+257",
      alternativePhoneCodes: [],
      iso2Code: "BI",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Cambodia",
      phoneCode: "+855",
      alternativePhoneCodes: [],
      iso2Code: "KH",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Cameroon",
      phoneCode: "+237",
      alternativePhoneCodes: [],
      iso2Code: "CM",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Canada",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1204",
        "+1236",
        "+1226",
        "+1306",
        "+1367",
        "+1403",
        "+1506",
        "+1709",
        "+1782",
        "+1867",
      ],
      iso2Code: "CA",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Cape Verde",
      phoneCode: "+238",
      alternativePhoneCodes: [],
      iso2Code: "CV",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Cayman Islands",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1345",
      ],
      iso2Code: "KY",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Central African Republic",
      phoneCode: "+236",
      alternativePhoneCodes: [],
      iso2Code: "CF",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Chad",
      phoneCode: "+235",
      alternativePhoneCodes: [],
      iso2Code: "TD",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Chile",
      phoneCode: "+56",
      alternativePhoneCodes: [],
      iso2Code: "CL",
      mask: "+## ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "China",
      phoneCode: "+86",
      alternativePhoneCodes: [],
      iso2Code: "CN",
      mask: "+## ### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Christmas Island",
      phoneCode: "+61",
      alternativePhoneCodes: [],
      iso2Code: "CX",
      mask: "+## # #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Colombia",
      phoneCode: "+57",
      alternativePhoneCodes: [],
      iso2Code: "CO",
      mask: "+## ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Comoros",
      phoneCode: "+269",
      alternativePhoneCodes: [],
      iso2Code: "KM",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Congo",
      phoneCode: "+242",
      alternativePhoneCodes: [],
      iso2Code: "CG",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Cook Islands",
      phoneCode: "+682",
      alternativePhoneCodes: [],
      iso2Code: "CK",
      mask: "+### ## ###",
    ),
    PhoneNumberMaskCountry(
      title: "Costa Rica",
      phoneCode: "+506",
      alternativePhoneCodes: [],
      iso2Code: "CR",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Croatia",
      phoneCode: "+385",
      alternativePhoneCodes: [],
      iso2Code: "HR",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Cuba",
      phoneCode: "+53",
      alternativePhoneCodes: [],
      iso2Code: "CU",
      mask: "+## ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Cyprus",
      phoneCode: "+357",
      alternativePhoneCodes: [],
      iso2Code: "CY",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Czech Republic",
      phoneCode: "+420",
      alternativePhoneCodes: [],
      iso2Code: "CZ",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Denmark",
      phoneCode: "+45",
      alternativePhoneCodes: [],
      iso2Code: "DK",
      mask: "+## # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Djibouti",
      phoneCode: "+253",
      alternativePhoneCodes: [],
      iso2Code: "DJ",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Dominica",
      phoneCode: "+1767",
      alternativePhoneCodes: [],
      iso2Code: "DM",
      mask: "+#### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Dominican Republic",
      phoneCode: "+1809",
      alternativePhoneCodes: [],
      iso2Code: "DO",
      mask: "+#### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Ecuador",
      phoneCode: "+593",
      alternativePhoneCodes: [],
      iso2Code: "EC",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Egypt",
      phoneCode: "+20",
      alternativePhoneCodes: [],
      iso2Code: "EG",
      mask: "+## ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "El Salvador",
      phoneCode: "+503",
      alternativePhoneCodes: [],
      iso2Code: "SV",
      mask: "+### ## #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Equatorial Guinea",
      phoneCode: "+240",
      alternativePhoneCodes: [],
      iso2Code: "GQ",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Eritrea",
      phoneCode: "+291",
      alternativePhoneCodes: [],
      iso2Code: "ER",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Estonia",
      phoneCode: "+372",
      alternativePhoneCodes: [],
      iso2Code: "EE",
      mask: "+### ### ###",
    ),
    PhoneNumberMaskCountry(
      title: "Ethiopia",
      phoneCode: "+251",
      alternativePhoneCodes: [],
      iso2Code: "ET",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Faroe Islands",
      phoneCode: "+298",
      alternativePhoneCodes: [],
      iso2Code: "FO",
      mask: "+### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Fiji",
      phoneCode: "+679",
      alternativePhoneCodes: [],
      iso2Code: "FJ",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Finland",
      phoneCode: "+358",
      alternativePhoneCodes: [],
      iso2Code: "FI",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "France",
      phoneCode: "+33",
      alternativePhoneCodes: [],
      iso2Code: "FR",
      mask: "+## # ## ## ## ##",
    ),
    PhoneNumberMaskCountry(
      title: "French Guiana",
      phoneCode: "+594",
      alternativePhoneCodes: [],
      iso2Code: "GF",
      mask: "+### ### ## ## ##",
    ),
    PhoneNumberMaskCountry(
      title: "French Polynesia",
      phoneCode: "+689",
      alternativePhoneCodes: [],
      iso2Code: "PF",
      mask: "+### ## ## ## ##",
    ),
    PhoneNumberMaskCountry(
      title: "Gabon",
      phoneCode: "+241",
      alternativePhoneCodes: [],
      iso2Code: "GA",
      mask: "+### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Gambia",
      phoneCode: "+220",
      alternativePhoneCodes: [],
      iso2Code: "GM",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Georgia",
      phoneCode: "+995",
      alternativePhoneCodes: [],
      iso2Code: "GE",
      mask: "+### ### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Germany",
      phoneCode: "+49",
      alternativePhoneCodes: [],
      iso2Code: "DE",
      mask: "+## ## #########",
    ),
    PhoneNumberMaskCountry(
      title: "Ghana",
      phoneCode: "+233",
      alternativePhoneCodes: [],
      iso2Code: "GH",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Gibraltar",
      phoneCode: "+350",
      alternativePhoneCodes: [],
      iso2Code: "GI",
      mask: "+### #####",
    ),
    PhoneNumberMaskCountry(
      title: "Greece",
      phoneCode: "+30",
      alternativePhoneCodes: [],
      iso2Code: "GR",
      mask: "+## # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Greenland",
      phoneCode: "+299",
      alternativePhoneCodes: [],
      iso2Code: "GL",
      mask: "+### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Grenada",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1473",
      ],
      iso2Code: "GD",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Guadeloupe",
      phoneCode: "+590",
      alternativePhoneCodes: [],
      iso2Code: "GP",
      mask: "+### ### ## ## ##",
    ),
    PhoneNumberMaskCountry(
      title: "Guam",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1671",
      ],
      iso2Code: "GU",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Guatemala",
      phoneCode: "+502",
      alternativePhoneCodes: [],
      iso2Code: "GT",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Guinea",
      phoneCode: "+224",
      alternativePhoneCodes: [],
      iso2Code: "GN",
      mask: "+### ### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Guinea-Bissau",
      phoneCode: "+245",
      alternativePhoneCodes: [],
      iso2Code: "GW",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Guyana",
      phoneCode: "+592",
      alternativePhoneCodes: [],
      iso2Code: "GY",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Haiti",
      phoneCode: "+509",
      alternativePhoneCodes: [],
      iso2Code: "HT",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Honduras",
      phoneCode: "+504",
      alternativePhoneCodes: [],
      iso2Code: "HN",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Hungary",
      phoneCode: "+36",
      alternativePhoneCodes: [],
      iso2Code: "HU",
      mask: "+## # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Hungary (Alternative)",
      phoneCode: "+06",
      alternativePhoneCodes: [],
      iso2Code: "HU",
      mask: "+## # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Iceland",
      phoneCode: "+354",
      alternativePhoneCodes: [],
      iso2Code: "IS",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "India",
      phoneCode: "+91",
      alternativePhoneCodes: [],
      iso2Code: "IN",
      mask: "+## ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Indonesia",
      phoneCode: "+62",
      alternativePhoneCodes: [],
      iso2Code: "ID",
      mask: "+## ## #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Iraq",
      phoneCode: "+964",
      alternativePhoneCodes: [],
      iso2Code: "IQ",
      mask: "+### (##) ### #####",
    ),
    PhoneNumberMaskCountry(
      title: "Ireland",
      phoneCode: "+353",
      alternativePhoneCodes: [],
      iso2Code: "IE",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Israel",
      phoneCode: "+972",
      alternativePhoneCodes: [],
      iso2Code: "IL",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Italy",
      phoneCode: "+39",
      alternativePhoneCodes: [],
      iso2Code: "IT",
      mask: "+## ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Jamaica",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1876",
      ],
      iso2Code: "JM",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Japan",
      phoneCode: "+81",
      alternativePhoneCodes: [],
      iso2Code: "JP",
      mask: "+## ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Jordan",
      phoneCode: "+962",
      alternativePhoneCodes: [],
      iso2Code: "JO",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Kazakhstan",
      phoneCode: "+7",
      alternativePhoneCodes: [
        "+87",
        "+77",
        "+76",
      ],
      iso2Code: "KZ",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Kenya",
      phoneCode: "+254",
      alternativePhoneCodes: [],
      iso2Code: "KE",
      mask: "+### ### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Kiribati",
      phoneCode: "+686",
      alternativePhoneCodes: [],
      iso2Code: "KI",
      mask: "+### #####",
    ),
    PhoneNumberMaskCountry(
      title: "Kuwait",
      phoneCode: "+965",
      alternativePhoneCodes: [],
      iso2Code: "KW",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Kyrgyzstan",
      phoneCode: "+996",
      alternativePhoneCodes: [],
      iso2Code: "KG",
      mask: "+### ### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Latvia",
      phoneCode: "+371",
      alternativePhoneCodes: [],
      iso2Code: "LV",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Lebanon",
      phoneCode: "+961",
      alternativePhoneCodes: [],
      iso2Code: "LB",
      mask: "+### ## ### ###",
    ),
    PhoneNumberMaskCountry(
      title: "Lesotho",
      phoneCode: "+266",
      alternativePhoneCodes: [],
      iso2Code: "LS",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Liberia",
      phoneCode: "+231",
      alternativePhoneCodes: [],
      iso2Code: "LR",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Liechtenstein",
      phoneCode: "+423",
      alternativePhoneCodes: [],
      iso2Code: "LI",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Lithuania",
      phoneCode: "+370",
      alternativePhoneCodes: [],
      iso2Code: "LT",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Luxembourg",
      phoneCode: "+352",
      alternativePhoneCodes: [],
      iso2Code: "LU",
      mask: "+### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Madagascar",
      phoneCode: "+261",
      alternativePhoneCodes: [],
      iso2Code: "MG",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Malawi",
      phoneCode: "+265",
      alternativePhoneCodes: [],
      iso2Code: "MW",
      mask: "+### #########",
    ),
    PhoneNumberMaskCountry(
      title: "Malaysia",
      phoneCode: "+60",
      alternativePhoneCodes: [],
      iso2Code: "MY",
      mask: "+## # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Maldives",
      phoneCode: "+960",
      alternativePhoneCodes: [],
      iso2Code: "MV",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Mali",
      phoneCode: "+223",
      alternativePhoneCodes: [],
      iso2Code: "ML",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Malta",
      phoneCode: "+356",
      alternativePhoneCodes: [],
      iso2Code: "MT",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Marshall Islands",
      phoneCode: "+692",
      alternativePhoneCodes: [],
      iso2Code: "MH",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Martinique",
      phoneCode: "+596",
      alternativePhoneCodes: [],
      iso2Code: "MQ",
      mask: "+### ### ## ## ##",
    ),
    PhoneNumberMaskCountry(
      title: "Mauritania",
      phoneCode: "+222",
      alternativePhoneCodes: [],
      iso2Code: "MR",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Mauritius",
      phoneCode: "+230",
      alternativePhoneCodes: [],
      iso2Code: "MU",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Mayotte",
      phoneCode: "+262",
      alternativePhoneCodes: [
        "+262269",
        "+262639",
      ],
      iso2Code: "YT",
      mask: "+### ### ## ## ##",
    ),
    PhoneNumberMaskCountry(
      title: "Mexico",
      phoneCode: "+52",
      alternativePhoneCodes: [],
      iso2Code: "MX",
      mask: "+## ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Monaco",
      phoneCode: "+377",
      alternativePhoneCodes: [],
      iso2Code: "MC",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Mongolia",
      phoneCode: "+976",
      alternativePhoneCodes: [],
      iso2Code: "MN",
      mask: "+### ## ######",
    ),
    PhoneNumberMaskCountry(
      title: "Montenegro",
      phoneCode: "+382",
      alternativePhoneCodes: [],
      iso2Code: "ME",
      mask: "+### ## ######",
    ),
    PhoneNumberMaskCountry(
      title: "Montserrat",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1664",
      ],
      iso2Code: "MS",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Morocco",
      phoneCode: "+212",
      alternativePhoneCodes: [],
      iso2Code: "MA",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Myanmar",
      phoneCode: "+95",
      alternativePhoneCodes: [],
      iso2Code: "MM",
      mask: "+## ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Namibia",
      phoneCode: "+264",
      alternativePhoneCodes: [],
      iso2Code: "NA",
      mask: "+### ## ######",
    ),
    PhoneNumberMaskCountry(
      title: "Nauru",
      phoneCode: "+674",
      alternativePhoneCodes: [],
      iso2Code: "NR",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Nepal",
      phoneCode: "+977",
      alternativePhoneCodes: [],
      iso2Code: "NP",
      mask: "+### ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Netherlands",
      phoneCode: "+31",
      alternativePhoneCodes: [],
      iso2Code: "NL",
      mask: "+## ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Netherlands Antilles",
      phoneCode: "+599",
      alternativePhoneCodes: [],
      iso2Code: "AN",
      mask: "+### ########",
    ),
    PhoneNumberMaskCountry(
      title: "New Caledonia",
      phoneCode: "+687",
      alternativePhoneCodes: [],
      iso2Code: "NC",
      mask: "+### ######",
    ),
    PhoneNumberMaskCountry(
      title: "New Zealand",
      phoneCode: "+64",
      alternativePhoneCodes: [],
      iso2Code: "NZ",
      mask: "+## (#) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Nicaragua",
      phoneCode: "+505",
      alternativePhoneCodes: [],
      iso2Code: "NI",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Niger",
      phoneCode: "+227",
      alternativePhoneCodes: [],
      iso2Code: "NE",
      mask: "+### ## ######",
    ),
    PhoneNumberMaskCountry(
      title: "Nigeria",
      phoneCode: "+234",
      alternativePhoneCodes: [],
      iso2Code: "NG",
      mask: "+### ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Niue",
      phoneCode: "+683",
      alternativePhoneCodes: [],
      iso2Code: "NU",
      mask: "+### #######",
    ),
    PhoneNumberMaskCountry(
      title: "Norfolk Island",
      phoneCode: "+672",
      alternativePhoneCodes: [],
      iso2Code: "NF",
      mask: "+### # ## ###",
    ),
    PhoneNumberMaskCountry(
      title: "Northern Mariana Islands",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1670",
      ],
      iso2Code: "MP",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Norway",
      phoneCode: "+47",
      alternativePhoneCodes: [],
      iso2Code: "NO",
      mask: "+## #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Oman",
      phoneCode: "+968",
      alternativePhoneCodes: [],
      iso2Code: "OM",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Pakistan",
      phoneCode: "+92",
      alternativePhoneCodes: [],
      iso2Code: "PK",
      mask: "+## ### #######",
    ),
    PhoneNumberMaskCountry(
      title: "Palau",
      phoneCode: "+680",
      alternativePhoneCodes: [],
      iso2Code: "PW",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Panama",
      phoneCode: "+507",
      alternativePhoneCodes: [],
      iso2Code: "PA",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Papua New Guinea",
      phoneCode: "+675",
      alternativePhoneCodes: [],
      iso2Code: "PG",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Paraguay",
      phoneCode: "+595",
      alternativePhoneCodes: [],
      iso2Code: "PY",
      mask: "+### ### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Peru",
      phoneCode: "+51",
      alternativePhoneCodes: [],
      iso2Code: "PE",
      mask: "+## ## #########",
    ),
    PhoneNumberMaskCountry(
      title: "Philippines",
      phoneCode: "+63",
      alternativePhoneCodes: [],
      iso2Code: "PH",
      mask: "+## ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Poland",
      phoneCode: "+48",
      alternativePhoneCodes: [],
      iso2Code: "PL",
      mask: "+## ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Portugal",
      phoneCode: "+351",
      alternativePhoneCodes: [],
      iso2Code: "PT",
      mask: "+### ### ### ###",
    ),
    PhoneNumberMaskCountry(
      title: "Puerto Rico",
      phoneCode: "+1939",
      alternativePhoneCodes: [],
      iso2Code: "PR",
      mask: "+#### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Qatar",
      phoneCode: "+974",
      alternativePhoneCodes: [],
      iso2Code: "QA",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Romania",
      phoneCode: "+40",
      alternativePhoneCodes: [],
      iso2Code: "RO",
      mask: "+## ### ### ###",
    ),
    PhoneNumberMaskCountry(
      title: "Rwanda",
      phoneCode: "+250",
      alternativePhoneCodes: [],
      iso2Code: "RW",
      mask: "### ### ###",
    ),
    PhoneNumberMaskCountry(
      title: "Samoa",
      phoneCode: "+685",
      alternativePhoneCodes: [],
      iso2Code: "WS",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "San Marino",
      phoneCode: "+378",
      alternativePhoneCodes: [],
      iso2Code: "SM",
      mask: "+### #### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Saudi Arabia",
      phoneCode: "+966",
      alternativePhoneCodes: [],
      iso2Code: "SA",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Senegal",
      phoneCode: "+221",
      alternativePhoneCodes: [],
      iso2Code: "SN",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Serbia",
      phoneCode: "+381",
      alternativePhoneCodes: [],
      iso2Code: "RS",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Seychelles",
      phoneCode: "+248",
      alternativePhoneCodes: [],
      iso2Code: "SC",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Sierra Leone",
      phoneCode: "+232",
      alternativePhoneCodes: [],
      iso2Code: "SL",
      mask: "+### ## ######",
    ),
    PhoneNumberMaskCountry(
      title: "Singapore",
      phoneCode: "+65",
      alternativePhoneCodes: [],
      iso2Code: "SG",
      mask: "+## #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Slovakia",
      phoneCode: "+421",
      alternativePhoneCodes: [],
      iso2Code: "SK",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Slovenia",
      phoneCode: "+386",
      alternativePhoneCodes: [],
      iso2Code: "SI",
      mask: "+### # ### ## ##",
    ),
    PhoneNumberMaskCountry(
      title: "Solomon Islands",
      phoneCode: "+677",
      alternativePhoneCodes: [],
      iso2Code: "SB",
      mask: "+### #####",
    ),
    PhoneNumberMaskCountry(
      title: "South Africa",
      phoneCode: "+27",
      alternativePhoneCodes: [],
      iso2Code: "ZA",
      mask: "+## ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Spain",
      phoneCode: "+34",
      alternativePhoneCodes: [],
      iso2Code: "ES",
      mask: "+## ### ### ###",
    ),
    PhoneNumberMaskCountry(
      title: "Sri Lanka",
      phoneCode: "+94",
      alternativePhoneCodes: [],
      iso2Code: "LK",
      mask: "+## ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Sudan",
      phoneCode: "+249",
      alternativePhoneCodes: [],
      iso2Code: "SD",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Suriname",
      phoneCode: "+597",
      alternativePhoneCodes: [],
      iso2Code: "SR",
      mask: "+### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Swaziland",
      phoneCode: "+268",
      alternativePhoneCodes: [],
      iso2Code: "SZ",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Sweden",
      phoneCode: "+46",
      alternativePhoneCodes: [],
      iso2Code: "SE",
      mask: "+## ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Switzerland",
      phoneCode: "+41",
      alternativePhoneCodes: [],
      iso2Code: "CH",
      mask: "+## ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Tajikistan",
      phoneCode: "+992",
      alternativePhoneCodes: [],
      iso2Code: "TJ",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Thailand",
      phoneCode: "+66",
      alternativePhoneCodes: [],
      iso2Code: "TH",
      mask: "+## # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Togo",
      phoneCode: "+228",
      alternativePhoneCodes: [],
      iso2Code: "TG",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Tokelau",
      phoneCode: "+690",
      alternativePhoneCodes: [],
      iso2Code: "TK",
      mask: "+### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Tonga",
      phoneCode: "+676",
      alternativePhoneCodes: [],
      iso2Code: "TO",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Trinidad and Tobago",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1868",
      ],
      iso2Code: "TT",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Tunisia",
      phoneCode: "+216",
      alternativePhoneCodes: [],
      iso2Code: "TN",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Turkey",
      phoneCode: "+90",
      alternativePhoneCodes: [],
      iso2Code: "TR",
      mask: "+## ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Turkmenistan",
      phoneCode: "+993",
      alternativePhoneCodes: [],
      iso2Code: "TM",
      mask: "+### ## ######",
    ),
    PhoneNumberMaskCountry(
      title: "Turks and Caicos Islands",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1649",
      ],
      iso2Code: "TC",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Tuvalu",
      phoneCode: "+688",
      alternativePhoneCodes: [],
      iso2Code: "TV",
      mask: "+### #####",
    ),
    PhoneNumberMaskCountry(
      title: "Uganda",
      phoneCode: "+256",
      alternativePhoneCodes: [],
      iso2Code: "UG",
      mask: "+### ### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Ukraine",
      phoneCode: "+380",
      alternativePhoneCodes: [],
      iso2Code: "UA",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "United Arab Emirates",
      phoneCode: "+971",
      alternativePhoneCodes: [],
      iso2Code: "AE",
      mask: "+### ## ######",
    ),
    PhoneNumberMaskCountry(
      title: "United Kingdom",
      phoneCode: "+44",
      alternativePhoneCodes: [
        "+447",
      ],
      iso2Code: "GB",
      mask: "+## #### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Uruguay",
      phoneCode: "+598",
      alternativePhoneCodes: [],
      iso2Code: "UY",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Uzbekistan",
      phoneCode: "+998",
      alternativePhoneCodes: [],
      iso2Code: "UZ",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Vanuatu",
      phoneCode: "+678",
      alternativePhoneCodes: [],
      iso2Code: "VU",
      mask: "+### #####",
    ),
    PhoneNumberMaskCountry(
      title: "Wallis and Futuna",
      phoneCode: "+681",
      alternativePhoneCodes: [],
      iso2Code: "WF",
      mask: "+### ## ####",
    ),
    PhoneNumberMaskCountry(
      title: "Yemen",
      phoneCode: "+967",
      alternativePhoneCodes: [],
      iso2Code: "YE",
      mask: "+### # ######",
    ),
    PhoneNumberMaskCountry(
      title: "Zambia",
      phoneCode: "+26#",
      alternativePhoneCodes: [],
      iso2Code: "ZM",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Zimbabwe",
      phoneCode: "+263",
      alternativePhoneCodes: [],
      iso2Code: "ZW",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Bolivia, Plurinational State of",
      phoneCode: "+591",
      alternativePhoneCodes: [],
      iso2Code: "BO",
      mask: "+### ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Brunei Darussalam",
      phoneCode: "+673",
      alternativePhoneCodes: [],
      iso2Code: "BN",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Congo, The Democratic Republic of the",
      phoneCode: "+243",
      alternativePhoneCodes: [],
      iso2Code: "CD",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Cote d\"Ivoire",
      phoneCode: "+225",
      alternativePhoneCodes: [],
      iso2Code: "CI",
      mask: "+### ########",
    ),
    PhoneNumberMaskCountry(
      title: "Falkland Islands (Malvinas)",
      phoneCode: "+500",
      alternativePhoneCodes: [],
      iso2Code: "FK",
      mask: "+### #####",
    ),
    PhoneNumberMaskCountry(
      title: "Guernsey",
      phoneCode: "+44",
      alternativePhoneCodes: [
        "+441534",
        "+447700",
        "+447797",
        "+447829",
        "+447937",
      ],
      iso2Code: "GG",
      mask: "+## (#) #### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Hong Kong",
      phoneCode: "+852",
      alternativePhoneCodes: [],
      iso2Code: "HK",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Iran, Islamic Republic of",
      phoneCode: "+98",
      alternativePhoneCodes: [],
      iso2Code: "IR",
      mask: "+## ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Korea, Democratic People\"s Republic of",
      phoneCode: "+850",
      alternativePhoneCodes: [],
      iso2Code: "KP",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Korea, Republic of",
      phoneCode: "+82",
      alternativePhoneCodes: [],
      iso2Code: "KR",
      mask: "+## # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "(Laos) Lao People\"s Democratic Republic",
      phoneCode: "+856",
      alternativePhoneCodes: [],
      iso2Code: "LA",
      mask: "+### ## #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Libyan Arab Jamahiriya",
      phoneCode: "+218",
      alternativePhoneCodes: [],
      iso2Code: "LY",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Macao",
      phoneCode: "+853",
      alternativePhoneCodes: [],
      iso2Code: "MO",
      mask: "+### #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Macedonia",
      phoneCode: "+389",
      alternativePhoneCodes: [],
      iso2Code: "MK",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Micronesia, Federated States of",
      phoneCode: "+691",
      alternativePhoneCodes: [],
      iso2Code: "FM",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Moldova, Republic of",
      phoneCode: "+373",
      alternativePhoneCodes: [],
      iso2Code: "MD",
      mask: "+### ### #####",
    ),
    PhoneNumberMaskCountry(
      title: "Mozambique",
      phoneCode: "+258",
      alternativePhoneCodes: [],
      iso2Code: "MZ",
      mask: "+### ### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Palestina",
      phoneCode: "+970",
      alternativePhoneCodes: [],
      iso2Code: "PS",
      mask: "+### # ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Réunion Island",
      phoneCode: "+262",
      alternativePhoneCodes: [
        "+262262",
        "+262263",
        "+262692",
        "+262693",
        "+262976",
      ],
      iso2Code: "RE",
      mask: "+### ### ## ## ##",
    ),
    PhoneNumberMaskCountry(
      title: "Russian Federation",
      phoneCode: "+7",
      alternativePhoneCodes: [
        "+89",
        "+88",
        "+83",
        "+84",
        "+79",
      ],
      iso2Code: "RU",
      mask: "+# (###) ###-##-##",
    ),
    PhoneNumberMaskCountry(
      title: "Saint Barthélemy",
      phoneCode: "+590",
      alternativePhoneCodes: [],
      iso2Code: "BL",
      mask: "+### ### ## ## ##",
    ),
    PhoneNumberMaskCountry(
      title: "Saint Helena, Ascension and Tristan Da Cunha",
      phoneCode: "+290",
      alternativePhoneCodes: [],
      iso2Code: "SH",
      mask: "+### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Saint Kitts and Nevis",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1869",
      ],
      iso2Code: "KN",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Saint Lucia",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1758",
      ],
      iso2Code: "LC",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Saint Martin",
      phoneCode: "+590",
      alternativePhoneCodes: [],
      iso2Code: "MF",
      mask: "+### ### ######",
    ),
    PhoneNumberMaskCountry(
      title: "Saint Pierre and Miquelon",
      phoneCode: "+508",
      alternativePhoneCodes: [],
      iso2Code: "PM",
      mask: "+### ## ## ##",
    ),
    PhoneNumberMaskCountry(
      title: "Saint Vincent and the Grenadines",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1784",
      ],
      iso2Code: "VC",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Sao Tome and Principe",
      phoneCode: "+239",
      alternativePhoneCodes: [],
      iso2Code: "ST",
      mask: "+### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Somalia",
      phoneCode: "+252",
      alternativePhoneCodes: [],
      iso2Code: "SO",
      mask: "+### ## ### ###",
    ),
    PhoneNumberMaskCountry(
      title: "Syrian Arab Republic",
      phoneCode: "+963",
      alternativePhoneCodes: [],
      iso2Code: "SY",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Taiwan",
      phoneCode: "+886",
      alternativePhoneCodes: [],
      iso2Code: "TW",
      mask: "+### # #### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Tanzania",
      phoneCode: "+255",
      alternativePhoneCodes: [],
      iso2Code: "TZ",
      mask: "+### ## ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Timor-Leste",
      phoneCode: "+670",
      alternativePhoneCodes: [],
      iso2Code: "TL",
      mask: "+### ### ###",
    ),
    PhoneNumberMaskCountry(
      title: "Venezuela, Bolivarian Republic of",
      phoneCode: "+58",
      alternativePhoneCodes: [],
      iso2Code: "VE",
      mask: "+## ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Viet Nam",
      phoneCode: "+84",
      alternativePhoneCodes: [],
      iso2Code: "VN",
      mask: "+## ### ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Virgin Islands, British",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1284",
      ],
      iso2Code: "VG",
      mask: "+# (###) ### ####",
    ),
    PhoneNumberMaskCountry(
      title: "Virgin Islands, U.S.",
      phoneCode: "+1",
      alternativePhoneCodes: [
        "+1340",
      ],
      iso2Code: "VI",
      mask: "+# (###) ### ####",
    ),
  ];
}
