import 'package:phone_number_mask/src/data.dart';

class PhoneNumberMaskConstant {
  static const String defaultPhoneMask = "+### ### #### ####";

  static const List<PhoneNUmberMaskCountry> countries = [
    PhoneNUmberMaskCountry(
      title: "Afghanistan",
      phoneCode: "93",
      iso2Code: "AF",
      mask: "+## ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Albania",
      phoneCode: "355",
      iso2Code: "AL",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Algeria",
      phoneCode: "213",
      iso2Code: "DZ",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "American Samoa",
      phoneCode: "1684",
      iso2Code: "AS",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Andorra",
      phoneCode: "376",
      iso2Code: "AD",
      mask: "+### ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Angola",
      phoneCode: "244",
      iso2Code: "AO",
      mask: "+### #### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Anguilla",
      phoneCode: "1264",
      iso2Code: "AI",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Antigua and Barbuda",
      phoneCode: "1268",
      iso2Code: "AG",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Argentina",
      phoneCode: "54",
      iso2Code: "AR",
      mask: "+## # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Armenia",
      phoneCode: "374",
      iso2Code: "AM",
      mask: "+### ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Aruba",
      phoneCode: "297",
      iso2Code: "AW",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Australia",
      phoneCode: "61",
      iso2Code: "AU",
      mask: "+## #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Austria",
      phoneCode: "43",
      iso2Code: "AT",
      mask: "+## ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Azerbaijan",
      phoneCode: "994",
      iso2Code: "AZ",
      mask: "+### ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Bahamas",
      phoneCode: "1242",
      iso2Code: "BS",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Bahrain",
      phoneCode: "973",
      iso2Code: "BH",
      mask: "+### ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Bangladesh",
      phoneCode: "88#",
      iso2Code: "BD",
      mask: "+### ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Barbados",
      phoneCode: "1246",
      iso2Code: "BB",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Belarus",
      phoneCode: "375",
      iso2Code: "BY",
      mask: "+### (##) ###-##-##",
    ),
    PhoneNUmberMaskCountry(
      title: "Belgium",
      phoneCode: "32",
      iso2Code: "BE",
      mask: "+## ### ## ## ##",
    ),
    PhoneNUmberMaskCountry(
      title: "Belize",
      phoneCode: "5#1",
      iso2Code: "BZ",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Benin",
      phoneCode: "229",
      iso2Code: "BJ",
      mask: "+### ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Bermuda",
      phoneCode: "1441",
      iso2Code: "BM",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Bhutan",
      phoneCode: "975",
      iso2Code: "BT",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Bosnia and Herzegovina",
      phoneCode: "387",
      iso2Code: "BA",
      mask: "+### ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Botswana",
      phoneCode: "267",
      iso2Code: "BW",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Brazil",
      phoneCode: "55",
      iso2Code: "BR",
      mask: "+## (##) ####-####",
    ),
    PhoneNUmberMaskCountry(
      title: "British Indian Ocean Territory",
      phoneCode: "246",
      iso2Code: "IO",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Bulgaria",
      phoneCode: "359",
      iso2Code: "BG",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Burkina Faso",
      phoneCode: "226",
      iso2Code: "BF",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Burundi",
      phoneCode: "257",
      iso2Code: "BI",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Cambodia",
      phoneCode: "855",
      iso2Code: "KH",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Cameroon",
      phoneCode: "237",
      iso2Code: "CM",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "United States",
      phoneCode: "1",
      iso2Code: "US",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Canada",
      phoneCode: "1",
      iso2Code: "CA",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Cape Verde",
      phoneCode: "238",
      iso2Code: "CV",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Cayman Islands",
      phoneCode: "345",
      iso2Code: "KY",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Central African Republic",
      phoneCode: "236",
      iso2Code: "CF",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Chad",
      phoneCode: "235",
      iso2Code: "TD",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Chile",
      phoneCode: "56",
      iso2Code: "CL",
      mask: "+## ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "China",
      phoneCode: "86",
      iso2Code: "CN",
      mask: "+## ### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Christmas Island",
      phoneCode: "61",
      iso2Code: "CX",
      mask: "+## # #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Colombia",
      phoneCode: "57",
      iso2Code: "CO",
      mask: "+## ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Comoros",
      phoneCode: "269",
      iso2Code: "KM",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Congo",
      phoneCode: "242",
      iso2Code: "CG",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Cook Islands",
      phoneCode: "682",
      iso2Code: "CK",
      mask: "+682 ## ###",
    ),
    PhoneNUmberMaskCountry(
      title: "Costa Rica",
      phoneCode: "5#6",
      iso2Code: "CR",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Croatia",
      phoneCode: "385",
      iso2Code: "HR",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Cuba",
      phoneCode: "53",
      iso2Code: "CU",
      mask: "+## ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Cyprus",
      phoneCode: "357",
      iso2Code: "CY",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Czech Republic",
      phoneCode: "42#",
      iso2Code: "CZ",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Denmark",
      phoneCode: "45",
      iso2Code: "DK",
      mask: "+## # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Djibouti",
      phoneCode: "253",
      iso2Code: "DJ",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Dominica",
      phoneCode: "1767",
      iso2Code: "DM",
      mask: "+#### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Dominican Republic",
      phoneCode: "18#9",
      iso2Code: "DO",
      mask: "+#### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Ecuador",
      phoneCode: "593",
      iso2Code: "EC",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Egypt",
      phoneCode: "2#",
      iso2Code: "EG",
      mask: "+## ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "El Salvador",
      phoneCode: "5#3",
      iso2Code: "SV",
      mask: "+### ## #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Equatorial Guinea",
      phoneCode: "24#",
      iso2Code: "GQ",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Eritrea",
      phoneCode: "291",
      iso2Code: "ER",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Estonia",
      phoneCode: "372",
      iso2Code: "EE",
      mask: "+### ### ###",
    ),
    PhoneNUmberMaskCountry(
      title: "Ethiopia",
      phoneCode: "251",
      iso2Code: "ET",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Faroe Islands",
      phoneCode: "298",
      iso2Code: "FO",
      mask: "+### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Fiji",
      phoneCode: "679",
      iso2Code: "FJ",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Finland",
      phoneCode: "358",
      iso2Code: "FI",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "France",
      phoneCode: "33",
      iso2Code: "FR",
      mask: "+## # ## ## ## ##",
    ),
    PhoneNUmberMaskCountry(
      title: "French Guiana",
      phoneCode: "594",
      iso2Code: "GF",
      mask: "+### ### ## ## ##",
    ),
    PhoneNUmberMaskCountry(
      title: "French Polynesia",
      phoneCode: "689",
      iso2Code: "PF",
      mask: "+### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Gabon",
      phoneCode: "241",
      iso2Code: "GA",
      mask: "+### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Gambia",
      phoneCode: "22#",
      iso2Code: "GM",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Georgia",
      phoneCode: "995",
      iso2Code: "GE",
      mask: "+### ### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Germany",
      phoneCode: "49",
      iso2Code: "DE",
      mask: "+## ## #########",
    ),
    PhoneNUmberMaskCountry(
      title: "Ghana",
      phoneCode: "233",
      iso2Code: "GH",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Gibraltar",
      phoneCode: "35#",
      iso2Code: "GI",
      mask: "+### #####",
    ),
    PhoneNUmberMaskCountry(
      title: "Greece",
      phoneCode: "3#",
      iso2Code: "GR",
      mask: "+## # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Greenland",
      phoneCode: "299",
      iso2Code: "GL",
      mask: "+### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Grenada",
      phoneCode: "1473",
      iso2Code: "GD",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Guadeloupe",
      phoneCode: "59#",
      iso2Code: "GP",
      mask: "+### ### ## ## ##",
    ),
    PhoneNUmberMaskCountry(
      title: "Guam",
      phoneCode: "1671",
      iso2Code: "GU",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Guatemala",
      phoneCode: "5#2",
      iso2Code: "GT",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Guinea",
      phoneCode: "224",
      iso2Code: "GN",
      mask: "+### ### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Guinea-Bissau",
      phoneCode: "245",
      iso2Code: "GW",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Guyana",
      phoneCode: "592",
      iso2Code: "GY",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Haiti",
      phoneCode: "5#9",
      iso2Code: "HT",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Honduras",
      phoneCode: "5#4",
      iso2Code: "HN",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Hungary",
      phoneCode: "36",
      iso2Code: "HU",
      mask: "+## # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Hungary (Alternative)",
      phoneCode: "#6",
      iso2Code: "HU",
      mask: "+## # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Iceland",
      phoneCode: "354",
      iso2Code: "IS",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "India",
      phoneCode: "91",
      iso2Code: "IN",
      mask: "+## ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Indonesia",
      phoneCode: "62",
      iso2Code: "ID",
      mask: "+## ## #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Iraq",
      phoneCode: "964",
      iso2Code: "IQ",
      mask: "+### (##) ### #####",
    ),
    PhoneNUmberMaskCountry(
      title: "Ireland",
      phoneCode: "353",
      iso2Code: "IE",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Israel",
      phoneCode: "972",
      iso2Code: "IL",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Italy",
      phoneCode: "39",
      iso2Code: "IT",
      mask: "+## ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Jamaica",
      phoneCode: "1876",
      iso2Code: "JM",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Japan",
      phoneCode: "81",
      iso2Code: "JP",
      mask: "+## ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Jordan",
      phoneCode: "962",
      iso2Code: "JO",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Kazakhstan",
      phoneCode: "7",
      iso2Code: "KZ",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Kenya",
      phoneCode: "254",
      iso2Code: "KE",
      mask: "+### ### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Kiribati",
      phoneCode: "686",
      iso2Code: "KI",
      mask: "+### #####",
    ),
    PhoneNUmberMaskCountry(
      title: "Kuwait",
      phoneCode: "965",
      iso2Code: "KW",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Kyrgyzstan",
      phoneCode: "996",
      iso2Code: "KG",
      mask: "+### ### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Latvia",
      phoneCode: "371",
      iso2Code: "LV",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Lebanon",
      phoneCode: "961",
      iso2Code: "LB",
      mask: "+### ## ### ###",
    ),
    PhoneNUmberMaskCountry(
      title: "Lesotho",
      phoneCode: "266",
      iso2Code: "LS",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Liberia",
      phoneCode: "231",
      iso2Code: "LR",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Liechtenstein",
      phoneCode: "423",
      iso2Code: "LI",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Lithuania",
      phoneCode: "37#",
      iso2Code: "LT",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Luxembourg",
      phoneCode: "352",
      iso2Code: "LU",
      mask: "+### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Madagascar",
      phoneCode: "261",
      iso2Code: "MG",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Malawi",
      phoneCode: "265",
      iso2Code: "MW",
      mask: "+### #########",
    ),
    PhoneNUmberMaskCountry(
      title: "Malaysia",
      phoneCode: "6#",
      iso2Code: "MY",
      mask: "+## # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Maldives",
      phoneCode: "96#",
      iso2Code: "MV",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Mali",
      phoneCode: "223",
      iso2Code: "ML",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Malta",
      phoneCode: "356",
      iso2Code: "MT",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Marshall Islands",
      phoneCode: "692",
      iso2Code: "MH",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Martinique",
      phoneCode: "596",
      iso2Code: "MQ",
      mask: "+### ### ## ## ##",
    ),
    PhoneNUmberMaskCountry(
      title: "Mauritania",
      phoneCode: "222",
      iso2Code: "MR",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Mauritius",
      phoneCode: "23#",
      iso2Code: "MU",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Mayotte",
      phoneCode: "262",
      iso2Code: "YT",
      mask: "+### ### ## ## ##",
    ),
    PhoneNUmberMaskCountry(
      title: "Mexico",
      phoneCode: "52",
      iso2Code: "MX",
      mask: "+## ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Monaco",
      phoneCode: "377",
      iso2Code: "MC",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Mongolia",
      phoneCode: "976",
      iso2Code: "MN",
      mask: "+### ## ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Montenegro",
      phoneCode: "382",
      iso2Code: "ME",
      mask: "+### ## ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Montserrat",
      phoneCode: "1664",
      iso2Code: "MS",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Morocco",
      phoneCode: "212",
      iso2Code: "MA",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Myanmar",
      phoneCode: "95",
      iso2Code: "MM",
      mask: "+## ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Namibia",
      phoneCode: "264",
      iso2Code: "NA",
      mask: "+### ## ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Nauru",
      phoneCode: "674",
      iso2Code: "NR",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Nepal",
      phoneCode: "977",
      iso2Code: "NP",
      mask: "+### ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Netherlands",
      phoneCode: "31",
      iso2Code: "NL",
      mask: "+## ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Netherlands Antilles",
      phoneCode: "599",
      iso2Code: "AN",
      mask: "+### ########",
    ),
    PhoneNUmberMaskCountry(
      title: "New Caledonia",
      phoneCode: "687",
      iso2Code: "NC",
      mask: "+### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "New Zealand",
      phoneCode: "64",
      iso2Code: "NZ",
      mask: "+## (#) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Nicaragua",
      phoneCode: "5#5",
      iso2Code: "NI",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Niger",
      phoneCode: "227",
      iso2Code: "NE",
      mask: "+### ## ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Nigeria",
      phoneCode: "234",
      iso2Code: "NG",
      mask: "+### ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Niue",
      phoneCode: "683",
      iso2Code: "NU",
      mask: "+### #######",
    ),
    PhoneNUmberMaskCountry(
      title: "Norfolk Island",
      phoneCode: "672",
      iso2Code: "NF",
      mask: "+### # ## ###",
    ),
    PhoneNUmberMaskCountry(
      title: "Northern Mariana Islands",
      phoneCode: "167#",
      iso2Code: "MP",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Norway",
      phoneCode: "47",
      iso2Code: "NO",
      mask: "+## #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Oman",
      phoneCode: "968",
      iso2Code: "OM",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Pakistan",
      phoneCode: "92",
      iso2Code: "PK",
      mask: "+## ### #######",
    ),
    PhoneNUmberMaskCountry(
      title: "Palau",
      phoneCode: "68#",
      iso2Code: "PW",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Panama",
      phoneCode: "5#7",
      iso2Code: "PA",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Papua New Guinea",
      phoneCode: "675",
      iso2Code: "PG",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Paraguay",
      phoneCode: "595",
      iso2Code: "PY",
      mask: "+### ### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Peru",
      phoneCode: "51",
      iso2Code: "PE",
      mask: "+## ## #########",
    ),
    PhoneNUmberMaskCountry(
      title: "Philippines",
      phoneCode: "63",
      iso2Code: "PH",
      mask: "+## ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Poland",
      phoneCode: "48",
      iso2Code: "PL",
      mask: "+## ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Portugal",
      phoneCode: "351",
      iso2Code: "PT",
      mask: "+### ### ### ###",
    ),
    PhoneNUmberMaskCountry(
      title: "Puerto Rico",
      phoneCode: "1939",
      iso2Code: "PR",
      mask: "+#### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Qatar",
      phoneCode: "974",
      iso2Code: "QA",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Romania",
      phoneCode: "4#",
      iso2Code: "RO",
      mask: "+## ### ### ###",
    ),
    PhoneNUmberMaskCountry(
      title: "Rwanda",
      phoneCode: "25#",
      iso2Code: "RW",
      mask: "### ### ###",
    ),
    PhoneNUmberMaskCountry(
      title: "Samoa",
      phoneCode: "685",
      iso2Code: "WS",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "San Marino",
      phoneCode: "378",
      iso2Code: "SM",
      mask: "+### #### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Saudi Arabia",
      phoneCode: "966",
      iso2Code: "SA",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Senegal",
      phoneCode: "221",
      iso2Code: "SN",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Serbia",
      phoneCode: "381",
      iso2Code: "RS",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Seychelles",
      phoneCode: "248",
      iso2Code: "SC",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Sierra Leone",
      phoneCode: "232",
      iso2Code: "SL",
      mask: "+### ## ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Singapore",
      phoneCode: "65",
      iso2Code: "SG",
      mask: "+## #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Slovakia",
      phoneCode: "421",
      iso2Code: "SK",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Slovenia",
      phoneCode: "386",
      iso2Code: "SI",
      mask: "+### # ### ## ##",
    ),
    PhoneNUmberMaskCountry(
      title: "Solomon Islands",
      phoneCode: "677",
      iso2Code: "SB",
      mask: "+### #####",
    ),
    PhoneNUmberMaskCountry(
      title: "South Africa",
      phoneCode: "27",
      iso2Code: "ZA",
      mask: "+## ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "South Georgia and the South Sandwich Islands",
      phoneCode: "5##",
      iso2Code: "GS",
      mask: "+### #####",
    ),
    PhoneNUmberMaskCountry(
      title: "Spain",
      phoneCode: "34",
      iso2Code: "ES",
      mask: "+## ### ### ###",
    ),
    PhoneNUmberMaskCountry(
      title: "Sri Lanka",
      phoneCode: "94",
      iso2Code: "LK",
      mask: "+## ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Sudan",
      phoneCode: "249",
      iso2Code: "SD",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Suriname",
      phoneCode: "597",
      iso2Code: "SR",
      mask: "+### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Swaziland",
      phoneCode: "268",
      iso2Code: "SZ",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Sweden",
      phoneCode: "46",
      iso2Code: "SE",
      mask: "+## ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Switzerland",
      phoneCode: "41",
      iso2Code: "CH",
      mask: "+## ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Tajikistan",
      phoneCode: "992",
      iso2Code: "TJ",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Thailand",
      phoneCode: "66",
      iso2Code: "TH",
      mask: "+## # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Togo",
      phoneCode: "228",
      iso2Code: "TG",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Tokelau",
      phoneCode: "69#",
      iso2Code: "TK",
      mask: "+### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Tonga",
      phoneCode: "676",
      iso2Code: "TO",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Trinidad and Tobago",
      phoneCode: "1868",
      iso2Code: "TT",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Tunisia",
      phoneCode: "216",
      iso2Code: "TN",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Turkey",
      phoneCode: "9#",
      iso2Code: "TR",
      mask: "+## ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Turkmenistan",
      phoneCode: "993",
      iso2Code: "TM",
      mask: "+### ## ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Turks and Caicos Islands",
      phoneCode: "1649",
      iso2Code: "TC",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Tuvalu",
      phoneCode: "688",
      iso2Code: "TV",
      mask: "+### #####",
    ),
    PhoneNUmberMaskCountry(
      title: "Uganda",
      phoneCode: "256",
      iso2Code: "UG",
      mask: "+### ### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Ukraine",
      phoneCode: "38#",
      iso2Code: "UA",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "United Arab Emirates",
      phoneCode: "971",
      iso2Code: "AE",
      mask: "+### ## ######",
    ),
    PhoneNUmberMaskCountry(
      title: "United Kingdom",
      phoneCode: "44",
      iso2Code: "GB",
      mask: "+## #### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Uruguay",
      phoneCode: "598",
      iso2Code: "UY",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Uzbekistan",
      phoneCode: "998",
      iso2Code: "UZ",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Vanuatu",
      phoneCode: "678",
      iso2Code: "VU",
      mask: "+### #####",
    ),
    PhoneNUmberMaskCountry(
      title: "Wallis and Futuna",
      phoneCode: "681",
      iso2Code: "WF",
      mask: "‎+### ## ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Yemen",
      phoneCode: "967",
      iso2Code: "YE",
      mask: "+### # ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Zambia",
      phoneCode: "26#",
      iso2Code: "ZM",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Zimbabwe",
      phoneCode: "263",
      iso2Code: "ZW",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Land Islands",
      phoneCode: "354",
      iso2Code: "AX",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Bolivia, Plurinational State of",
      phoneCode: "591",
      iso2Code: "BO",
      mask: "+### ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Brunei Darussalam",
      phoneCode: "673",
      iso2Code: "BN",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Cocos (Keeling) Islands",
      phoneCode: "61",
      iso2Code: "CC",
      mask: "+## # #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Congo, The Democratic Republic of the",
      phoneCode: "243",
      iso2Code: "CD",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Cote d\"Ivoire",
      phoneCode: "225",
      iso2Code: "CI",
      mask: "+### ########",
    ),
    PhoneNUmberMaskCountry(
      title: "Falkland Islands (Malvinas)",
      phoneCode: "5##",
      iso2Code: "FK",
      mask: "+### #####",
    ),
    PhoneNUmberMaskCountry(
      title: "Guernsey",
      phoneCode: "44",
      iso2Code: "GG",
      mask: "+## (#) #### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Hong Kong",
      phoneCode: "852",
      iso2Code: "HK",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Iran, Islamic Republic of",
      phoneCode: "98",
      iso2Code: "IR",
      mask: "+## ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Korea, Democratic People\"s Republic of",
      phoneCode: "85#",
      iso2Code: "KP",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Korea, Republic of",
      phoneCode: "82",
      iso2Code: "KR",
      mask: "+## # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "(Laos) Lao People\"s Democratic Republic",
      phoneCode: "856",
      iso2Code: "LA",
      mask: "+### ## #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Libyan Arab Jamahiriya",
      phoneCode: "218",
      iso2Code: "LY",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Macao",
      phoneCode: "853",
      iso2Code: "MO",
      mask: "+### #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Macedonia",
      phoneCode: "389",
      iso2Code: "MK",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Micronesia, Federated States of",
      phoneCode: "691",
      iso2Code: "FM",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Moldova, Republic of",
      phoneCode: "373",
      iso2Code: "MD",
      mask: "+### ### #####",
    ),
    PhoneNUmberMaskCountry(
      title: "Mozambique",
      phoneCode: "258",
      iso2Code: "MZ",
      mask: "+### ### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Palestina",
      phoneCode: "97#",
      iso2Code: "PS",
      mask: "+### # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Pitcairn",
      phoneCode: "64",
      iso2Code: "PN",
      mask: "+## # ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Réunion",
      phoneCode: "262",
      iso2Code: "RE",
      mask: "+### ### ## ## ##",
    ),
    PhoneNUmberMaskCountry(
      title: "Russian Federation",
      phoneCode: "7",
      iso2Code: "RU",
      mask: "+# (###) ###-##-##",
    ),
    PhoneNUmberMaskCountry(
      title: "Saint Barthélemy",
      phoneCode: "59#",
      iso2Code: "BL",
      mask: "+### ### ## ## ##",
    ),
    PhoneNUmberMaskCountry(
      title: "Saint Helena, Ascension and Tristan Da Cunha",
      phoneCode: "29#",
      iso2Code: "SH",
      mask: "+### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Saint Kitts and Nevis",
      phoneCode: "1869",
      iso2Code: "KN",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Saint Lucia",
      phoneCode: "1758",
      iso2Code: "LC",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Saint Martin",
      phoneCode: "59#",
      iso2Code: "MF",
      mask: "+### ### ######",
    ),
    PhoneNUmberMaskCountry(
      title: "Saint Pierre and Miquelon",
      phoneCode: "5#8",
      iso2Code: "PM",
      mask: "+5#8 ## ## ##",
    ),
    PhoneNUmberMaskCountry(
      title: "Saint Vincent and the Grenadines",
      phoneCode: "1784",
      iso2Code: "VC",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Sao Tome and Principe",
      phoneCode: "239",
      iso2Code: "ST",
      mask: "+### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Somalia",
      phoneCode: "252",
      iso2Code: "SO",
      mask: "+### ## ### ###",
    ),
    PhoneNUmberMaskCountry(
      title: "Svalbard and Jan Mayen",
      phoneCode: "47",
      iso2Code: "SJ",
      mask: "+## #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Syrian Arab Republic",
      phoneCode: "963",
      iso2Code: "SY",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Taiwan",
      phoneCode: "886",
      iso2Code: "TW",
      mask: "+### # #### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Tanzania",
      phoneCode: "255",
      iso2Code: "TZ",
      mask: "+### ## ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Timor-Leste",
      phoneCode: "67#",
      iso2Code: "TL",
      mask: "+### ### ###",
    ),
    PhoneNUmberMaskCountry(
      title: "Venezuela, Bolivarian Republic of",
      phoneCode: "58",
      iso2Code: "VE",
      mask: "+## ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Viet Nam",
      phoneCode: "84",
      iso2Code: "VN",
      mask: "+## ### ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Virgin Islands, British",
      phoneCode: "1284",
      iso2Code: "VG",
      mask: "+# (###) ### ####",
    ),
    PhoneNUmberMaskCountry(
      title: "Virgin Islands, U.S.",
      phoneCode: "134#",
      iso2Code: "VI",
      mask: "+# (###) ### ####",
    ),
  ];
}
